kumuluzee:
  name: file-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/FileMetadataDS
      connection-url: jdbc:postgresql://abul.db.elephantsql.com/igkywmox
      username: igkywmox
      password: 2_pNpLTnwT-R-CVW86Zdc1CCkj5demVV
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/FileMetadataDS
      http-health-check:
        connection-url: http://localhost:8080/v1/files
  metrics:
    web-instrumentation:
      - name: files-endpoint
        url-pattern: /v1/files/*
rest-properties:
  maintenance-mode: false